version: '3.8'

services:
  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    command: celery -A app.celery_worker worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - redis

  test-fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./test.db
